name: 'aliyun-oss-website-action-for-gatsby'
description: 'Deploy your gatsby website on aliyun OSS'
author: 'Docacola <444984@qq.com>'
branding:
  icon: 'upload'
  color: 'gray-dark'
inputs:
  folder:
    description: 'Folder which contains the website files'
    required: true
  exclude:
    description: 'Exclude file from the folder'
    required: false
  accessKeyId:
    description: 'Aliyun OSS accessKeyId.'
    required: true
  accessKeySecret:
    description: 'Aliyun OSS accessKeySecret.'
    required: true
  bucket:
    description: 'Aliyun OSS bucket instance.'
    required: true
  endpoint:
    description: 'OSS region domain'
    required: true
  cname:
    description: '`true` to identify the endpoint is your custom domain.'
    required: false
    default: 'false'
  skipSetting:
    description: '`true` to skip setting static pages related configuration. `indexPage`, `notFoundPage` will not be used.'
    required: false
    default: 'false'
  indexPage:
    description: 'index page'
    required: false
    default: 'index.html'
  notFoundPage:
    description: 'not found page'
    required: false
    default: '404.html'
  htmlCacheControl:
    description: 'Cache-Control for HTML'
    required: false
    default: 'public, max-age=0, must-revalidate'
  imageCacheControl:
    description: 'Cache-Control for image'
    required: false
    default: 'public, max-age=31536000, immutable'
  pageDataCacheControl:
    description: 'Cache-Control for page-data'
    required: false
    default: 'public, max-age=0, must-revalidate'
  otherCacheControl:
    description: 'Cache-Control for other files'
    required: false
    default: 'public, max-age=31536000, immutable'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACCESS_KEY_ID: ${{ inputs.accessKeyId }}
    ACCESS_KEY_SECRET: ${{ inputs.accessKeySecret }}
    BUCKET: ${{ inputs.bucket }}
    ENDPOINT: ${{ inputs.endpoint }}
    CNAME: ${{ inputs.cname }}
    FOLDER: ${{ inputs.folder }}
    EXCLUDE: ${{ inputs.exclude }}
    SKIP_SETTING: ${{ inputs.skipSetting }}
    INDEX_PAGE: ${{ inputs.indexPage }}
    NOT_FOUND_PAGE: ${{ inputs.notFoundPage }}
    HTML_CACHE_CONTROL: ${{ inputs.htmlCacheControl }}
    IMAGE_CACHE_CONTROL: ${{ inputs.imageCacheControl }}
    OTHER_CACHE_CONTROL: ${{ inputs.otherCacheControl }}
    
